CREATE TABLE "user_contacts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"type" varchar(20) NOT NULL,
	"value" varchar(50) NOT NULL,
	CONSTRAINT "user_contacts_id_pk" PRIMARY KEY("id")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"full_name" varchar(255) NOT NULL,
	"mandarin_name" varchar(255),
	"gender" varchar(10),
	"birth_date" text,
	"address" text,
	"phone_whatsapp" varchar(20),
	"dhamma_1_day_completed" boolean DEFAULT false NOT NULL,
	"dhamma_3_day_completed" boolean DEFAULT false NOT NULL,
	"vegetarian_status" varchar(20) NOT NULL,
	"qr_code" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "vegetarian_statuses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vegetarian_statuses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL,
	CONSTRAINT "vegetarian_statuses_name_unique" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "user_contacts" ADD CONSTRAINT "user_contacts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;